server:
  port: 5005
spring:
  application:
    name: activity-server
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848
  config:
    import:
      - nacos:activity-server.yaml
